[".local/bin/n98-magerun2"]
    executable = true
    refreshPeriod = "24h"
    type = "file"
    url = "https://files.magerun.net/n98-magerun2.phar"

[".vim/autoload/plug.vim"]
    refreshPeriod = "168h"
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
